### ISSUE TITLE
Potential bug in glowIdentifier

### ISSUE THREAD

**Issue by adaly** [ellispatrick/AFidMatlab#1]
In lines 249-251 of glowIdentifier.m (and similarly in lines 253-255):

```
im1GlowRemoved = im1;
im1GlowRemoved(bw==0) = 0;
im1GlowRemoved(glow1) = 0;
```
The function sets all pixels **outside** the binary AF mask to 0 before removing the detected glow. This results in `imXGlowRemoved` containing **only** the AF signal with surrounding glow removed, instead of the image with both AF and surrounding glow removed. Is this the desired behavior? It seems that it would be more useful for a user attempting to remove an AF signal to receive a copy of `imXGlowRemoved` with `imXGlowRemoved(bw==1) = 0`.

**Comment by nickcee** [comment]
Fixed
